// Generated by gencpp from file th_messages/raw_elastometer.msg
// DO NOT EDIT!


#ifndef TH_MESSAGES_MESSAGE_RAW_ELASTOMETER_H
#define TH_MESSAGES_MESSAGE_RAW_ELASTOMETER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace th_messages
{
template <class ContainerAllocator>
struct raw_elastometer_
{
  typedef raw_elastometer_<ContainerAllocator> Type;

  raw_elastometer_()
    : header()
    , rows(0)
    , cols(0)
    , p_level()  {
    }
  raw_elastometer_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , rows(0)
    , cols(0)
    , p_level(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _rows_type;
  _rows_type rows;

   typedef uint8_t _cols_type;
  _cols_type cols;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _p_level_type;
  _p_level_type p_level;





  typedef boost::shared_ptr< ::th_messages::raw_elastometer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::th_messages::raw_elastometer_<ContainerAllocator> const> ConstPtr;

}; // struct raw_elastometer_

typedef ::th_messages::raw_elastometer_<std::allocator<void> > raw_elastometer;

typedef boost::shared_ptr< ::th_messages::raw_elastometer > raw_elastometerPtr;
typedef boost::shared_ptr< ::th_messages::raw_elastometer const> raw_elastometerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::th_messages::raw_elastometer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::th_messages::raw_elastometer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::th_messages::raw_elastometer_<ContainerAllocator1> & lhs, const ::th_messages::raw_elastometer_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.rows == rhs.rows &&
    lhs.cols == rhs.cols &&
    lhs.p_level == rhs.p_level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::th_messages::raw_elastometer_<ContainerAllocator1> & lhs, const ::th_messages::raw_elastometer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace th_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::th_messages::raw_elastometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::th_messages::raw_elastometer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::th_messages::raw_elastometer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::th_messages::raw_elastometer_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::th_messages::raw_elastometer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::th_messages::raw_elastometer_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::th_messages::raw_elastometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a25a3ba9a447cce9b672c660d7b15412";
  }

  static const char* value(const ::th_messages::raw_elastometer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa25a3ba9a447cce9ULL;
  static const uint64_t static_value2 = 0xb672c660d7b15412ULL;
};

template<class ContainerAllocator>
struct DataType< ::th_messages::raw_elastometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "th_messages/raw_elastometer";
  }

  static const char* value(const ::th_messages::raw_elastometer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::th_messages::raw_elastometer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint8 rows\n"
"uint8 cols\n"
"uint32[] p_level\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::th_messages::raw_elastometer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::th_messages::raw_elastometer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.rows);
      stream.next(m.cols);
      stream.next(m.p_level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct raw_elastometer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::th_messages::raw_elastometer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::th_messages::raw_elastometer_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "rows: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rows);
    s << indent << "cols: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cols);
    s << indent << "p_level[]" << std::endl;
    for (size_t i = 0; i < v.p_level.size(); ++i)
    {
      s << indent << "  p_level[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.p_level[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TH_MESSAGES_MESSAGE_RAW_ELASTOMETER_H
