// Generated by gencpp from file th_messages/raw_imu2.msg
// DO NOT EDIT!


#ifndef TH_MESSAGES_MESSAGE_RAW_IMU2_H
#define TH_MESSAGES_MESSAGE_RAW_IMU2_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace th_messages
{
template <class ContainerAllocator>
struct raw_imu2_
{
  typedef raw_imu2_<ContainerAllocator> Type;

  raw_imu2_()
    : header()
    , tempe()
    , ax()
    , ay()
    , az()
    , gx()
    , gy()
    , gz()
    , mx()
    , my()
    , mz()  {
    }
  raw_imu2_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tempe(_alloc)
    , ax(_alloc)
    , ay(_alloc)
    , az(_alloc)
    , gx(_alloc)
    , gy(_alloc)
    , gz(_alloc)
    , mx(_alloc)
    , my(_alloc)
    , mz(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tempe_type;
  _tempe_type tempe;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ax_type;
  _ax_type ax;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ay_type;
  _ay_type ay;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _az_type;
  _az_type az;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _gx_type;
  _gx_type gx;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _gy_type;
  _gy_type gy;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _gz_type;
  _gz_type gz;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mx_type;
  _mx_type mx;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _my_type;
  _my_type my;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _mz_type;
  _mz_type mz;





  typedef boost::shared_ptr< ::th_messages::raw_imu2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::th_messages::raw_imu2_<ContainerAllocator> const> ConstPtr;

}; // struct raw_imu2_

typedef ::th_messages::raw_imu2_<std::allocator<void> > raw_imu2;

typedef boost::shared_ptr< ::th_messages::raw_imu2 > raw_imu2Ptr;
typedef boost::shared_ptr< ::th_messages::raw_imu2 const> raw_imu2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::th_messages::raw_imu2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::th_messages::raw_imu2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::th_messages::raw_imu2_<ContainerAllocator1> & lhs, const ::th_messages::raw_imu2_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tempe == rhs.tempe &&
    lhs.ax == rhs.ax &&
    lhs.ay == rhs.ay &&
    lhs.az == rhs.az &&
    lhs.gx == rhs.gx &&
    lhs.gy == rhs.gy &&
    lhs.gz == rhs.gz &&
    lhs.mx == rhs.mx &&
    lhs.my == rhs.my &&
    lhs.mz == rhs.mz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::th_messages::raw_imu2_<ContainerAllocator1> & lhs, const ::th_messages::raw_imu2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace th_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::th_messages::raw_imu2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::th_messages::raw_imu2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::th_messages::raw_imu2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::th_messages::raw_imu2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::th_messages::raw_imu2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::th_messages::raw_imu2_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::th_messages::raw_imu2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fea683002c52f4a1ffae2fd1a0e778f";
  }

  static const char* value(const ::th_messages::raw_imu2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fea683002c52f4aULL;
  static const uint64_t static_value2 = 0x1ffae2fd1a0e778fULL;
};

template<class ContainerAllocator>
struct DataType< ::th_messages::raw_imu2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "th_messages/raw_imu2";
  }

  static const char* value(const ::th_messages::raw_imu2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::th_messages::raw_imu2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float32[] tempe\n"
"float32[] ax\n"
"float32[] ay\n"
"float32[] az\n"
"float32[] gx\n"
"float32[] gy\n"
"float32[] gz\n"
"float32[] mx\n"
"float32[] my\n"
"float32[] mz\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::th_messages::raw_imu2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::th_messages::raw_imu2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tempe);
      stream.next(m.ax);
      stream.next(m.ay);
      stream.next(m.az);
      stream.next(m.gx);
      stream.next(m.gy);
      stream.next(m.gz);
      stream.next(m.mx);
      stream.next(m.my);
      stream.next(m.mz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct raw_imu2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::th_messages::raw_imu2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::th_messages::raw_imu2_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tempe[]" << std::endl;
    for (size_t i = 0; i < v.tempe.size(); ++i)
    {
      s << indent << "  tempe[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tempe[i]);
    }
    s << indent << "ax[]" << std::endl;
    for (size_t i = 0; i < v.ax.size(); ++i)
    {
      s << indent << "  ax[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ax[i]);
    }
    s << indent << "ay[]" << std::endl;
    for (size_t i = 0; i < v.ay.size(); ++i)
    {
      s << indent << "  ay[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ay[i]);
    }
    s << indent << "az[]" << std::endl;
    for (size_t i = 0; i < v.az.size(); ++i)
    {
      s << indent << "  az[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.az[i]);
    }
    s << indent << "gx[]" << std::endl;
    for (size_t i = 0; i < v.gx.size(); ++i)
    {
      s << indent << "  gx[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gx[i]);
    }
    s << indent << "gy[]" << std::endl;
    for (size_t i = 0; i < v.gy.size(); ++i)
    {
      s << indent << "  gy[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gy[i]);
    }
    s << indent << "gz[]" << std::endl;
    for (size_t i = 0; i < v.gz.size(); ++i)
    {
      s << indent << "  gz[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gz[i]);
    }
    s << indent << "mx[]" << std::endl;
    for (size_t i = 0; i < v.mx.size(); ++i)
    {
      s << indent << "  mx[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.mx[i]);
    }
    s << indent << "my[]" << std::endl;
    for (size_t i = 0; i < v.my.size(); ++i)
    {
      s << indent << "  my[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.my[i]);
    }
    s << indent << "mz[]" << std::endl;
    for (size_t i = 0; i < v.mz.size(); ++i)
    {
      s << indent << "  mz[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.mz[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TH_MESSAGES_MESSAGE_RAW_IMU2_H
