// Generated by gencpp from file markers/obstacle.msg
// DO NOT EDIT!


#ifndef MARKERS_MESSAGE_OBSTACLE_H
#define MARKERS_MESSAGE_OBSTACLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace markers
{
template <class ContainerAllocator>
struct obstacle_
{
  typedef obstacle_<ContainerAllocator> Type;

  obstacle_()
    : obstacle(false)  {
    }
  obstacle_(const ContainerAllocator& _alloc)
    : obstacle(false)  {
  (void)_alloc;
    }



   typedef uint8_t _obstacle_type;
  _obstacle_type obstacle;





  typedef boost::shared_ptr< ::markers::obstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::markers::obstacle_<ContainerAllocator> const> ConstPtr;

}; // struct obstacle_

typedef ::markers::obstacle_<std::allocator<void> > obstacle;

typedef boost::shared_ptr< ::markers::obstacle > obstaclePtr;
typedef boost::shared_ptr< ::markers::obstacle const> obstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::markers::obstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::markers::obstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::markers::obstacle_<ContainerAllocator1> & lhs, const ::markers::obstacle_<ContainerAllocator2> & rhs)
{
  return lhs.obstacle == rhs.obstacle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::markers::obstacle_<ContainerAllocator1> & lhs, const ::markers::obstacle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace markers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::markers::obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::markers::obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::markers::obstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::markers::obstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::markers::obstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::markers::obstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::markers::obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e3182e1a5a09586299e547868ccbb8a";
  }

  static const char* value(const ::markers::obstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e3182e1a5a09586ULL;
  static const uint64_t static_value2 = 0x299e547868ccbb8aULL;
};

template<class ContainerAllocator>
struct DataType< ::markers::obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "markers/obstacle";
  }

  static const char* value(const ::markers::obstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::markers::obstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool obstacle\n"
;
  }

  static const char* value(const ::markers::obstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::markers::obstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct obstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::markers::obstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::markers::obstacle_<ContainerAllocator>& v)
  {
    s << indent << "obstacle: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARKERS_MESSAGE_OBSTACLE_H
