// Generated by gencpp from file sensor/magne.msg
// DO NOT EDIT!


#ifndef SENSOR_MESSAGE_MAGNE_H
#define SENSOR_MESSAGE_MAGNE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor
{
template <class ContainerAllocator>
struct magne_
{
  typedef magne_<ContainerAllocator> Type;

  magne_()
    : magne()  {
    }
  magne_(const ContainerAllocator& _alloc)
    : magne(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _magne_type;
  _magne_type magne;





  typedef boost::shared_ptr< ::sensor::magne_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor::magne_<ContainerAllocator> const> ConstPtr;

}; // struct magne_

typedef ::sensor::magne_<std::allocator<void> > magne;

typedef boost::shared_ptr< ::sensor::magne > magnePtr;
typedef boost::shared_ptr< ::sensor::magne const> magneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor::magne_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor::magne_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor::magne_<ContainerAllocator1> & lhs, const ::sensor::magne_<ContainerAllocator2> & rhs)
{
  return lhs.magne == rhs.magne;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor::magne_<ContainerAllocator1> & lhs, const ::sensor::magne_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensor::magne_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor::magne_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor::magne_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor::magne_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor::magne_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor::magne_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor::magne_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ad17479b92c9ce002f096e7afd3ccab";
  }

  static const char* value(const ::sensor::magne_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ad17479b92c9ce0ULL;
  static const uint64_t static_value2 = 0x02f096e7afd3ccabULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor::magne_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor/magne";
  }

  static const char* value(const ::sensor::magne_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor::magne_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] magne\n"
;
  }

  static const char* value(const ::sensor::magne_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor::magne_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.magne);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct magne_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor::magne_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor::magne_<ContainerAllocator>& v)
  {
    s << indent << "magne[]" << std::endl;
    for (size_t i = 0; i < v.magne.size(); ++i)
    {
      s << indent << "  magne[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.magne[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MESSAGE_MAGNE_H
